### ISSUE TITLE
Checklist: Community

### ISSUE THREAD

**Issue by edsondearaujo** [fga-eps-mds/2020-1-Ziguen#61]
| nome | assunto| titulo| label | assignees |
|------|------|------|------|-----|
| Checklist | Ficar em dia com a Checklist Community |  | documentation | @liversonp @francisco1code  | 

## Descrição

Resolver todas as dependências relacionadas à checklist community.

## Tarefa 

- [x] Descrição

- [x] README

- [x] código de conduta

- [x] Contribuindo

- [x] Licença

- [x] Template de Issue

- [ ] Template de Pull request

- [x] Os administradores do repositório aceitam reporte de conteúdo

**Comment by liversonp** [comment]
O github não nos deixou fazer o Pull Request template, ele já considerou como feito 100%, no meu e no do @francisco1code :cry: :cry: :cry:
