### ISSUE TITLE
Checklist entrega release 1

### ISSUE THREAD

**Issue by edsondearaujo** [fga-eps-mds/2020-1-Ziguen#74]
## Descrição
Fazer revisão de todos os conteúdos listados abaixo:

- [x] Documento de Visão do Projeto
- [x] Planejamento/Comunicação Interna e Externa (agenda de trabalho + ferramentas), Documento de Arquitetura do Projeto
- [x] Especificação das historias de usuários (critérios de aceitação)
- [x] Configuração do repositório de acordo com os padrões de comunidade de software livre (Github)
- [x] Wiki atualizada
- [x] Protótipo de alta fidelidade
- [x] Criar apresentação

## Critério de avaliação

- [x] Conclusão de todos os itens da lista acima

## Referência
- [ Issue no repositório da disciplina, apresentação da R1 ](https://github.com/fga-eps-mds/A-Disciplina/issues/79)
- [ Cronograma da disciplina](https://github.com/fga-eps-mds/A-Disciplina/blob/master/PlanosDeEnsino/MDS-cronograma-hrn.md)

**Comment by RochaCarla** [comment]
Aproveitem a apresentação para reforçar os pontos positivos do projeto de vocês (considerem que vamos ler toda a documentação e ver o código antes da R1)

**Comment by edsondearaujo** [comment]
Ok, professora.

**Comment by liversonp** [comment]
O que precisamos fazer:

- [x] organizar issue

- [x] criar epics

- [x] Preencher roadmap

- [x] Atualizar o documento de gerência de riscos

- [x] Mudar o diagrama da daily em metodologia

- [x] Atualizar roadmap da wiki

- [x] Adicionar a page ao about

- [x] atualizar diagrama representação da arquitetura

- [ ] Atualizar Page

**Comment by edsondearaujo** [comment]
Vou reabrir as issues listadas abaixo para fazer teste na criação do roadmap no zenhub.

***Estudo*** #75 
- #4 
- #5 
- #7 
- #8 
- #9 
- #10 
- #12 
- #15
